server:
  port: 8081


spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: refresh

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      com:
        darum: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /api/v1/auth/docs
  swagger-ui:
    path: /docs/swagger-ui.html