apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-config
    namespace: darum-staging
data:
    POSTGRES_DB: auth_db
    POSTGRES_USER: darum
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: darum-staging
type: Opaque
stringData:
    POSTGRES_PASSWORD: darum123 # Change in production
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-auth
    namespace: darum-staging
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres-auth
    template:
        metadata:
            labels:
                app: postgres-auth
        spec:
            containers:
                - name: postgres
                  image: postgres:16-alpine
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_DB
                        valueFrom:
                            configMapKeyRef:
                                name: postgres-config
                                key: POSTGRES_DB
                      - name: POSTGRES_USER
                        valueFrom:
                            configMapKeyRef:
                                name: postgres-config
                                key: POSTGRES_USER
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret
                                key: POSTGRES_PASSWORD
                  volumeMounts:
                      - name: postgres-storage
                        mountPath: /var/lib/postgresql/data
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "250m"
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
            volumes:
                - name: postgres-storage
                  persistentVolumeClaim:
                      claimName: postgres-auth-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: postgres-auth
    namespace: darum-staging
spec:
    selector:
        app: postgres-auth
    ports:
        - port: 5432
          targetPort: 5432
    type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-auth-pvc
    namespace: darum-staging
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
