name: Test Coverage Report

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop
    schedule:
        - cron: "0 0 * * 0" # Weekly on Sunday

jobs:
    coverage:
        name: Generate Coverage Report
        runs-on: ubuntu-latest

        strategy:
            matrix:
                service:
                    - auth-service
                    - employee-service

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"
                  cache: "maven"

            - name: Build shared-domain
              run: |
                  cd shared-domain
                  mvn clean install -DskipTests

            - name: Run tests with coverage
              run: |
                  cd ${{ matrix.service }}
                  mvn clean test jacoco:report

            - name: Generate coverage badge
              uses: cicirello/jacoco-badge-generator@v2
              with:
                  jacoco-csv-file: ${{ matrix.service }}/target/site/jacoco/jacoco.csv
                  badges-directory: .github/badges/${{ matrix.service }}
                  generate-branches-badge: true
                  generate-summary: true

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./${{ matrix.service }}/target/site/jacoco/jacoco.xml
                  flags: ${{ matrix.service }}
                  name: ${{ matrix.service }}-coverage
                  fail_ci_if_error: false

            - name: Upload coverage report
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-report-${{ matrix.service }}
                  path: ${{ matrix.service }}/target/site/jacoco/
                  retention-days: 30

            - name: Comment PR with coverage
              if: github.event_name == 'pull_request'
              uses: madrapps/jacoco-report@v1.6.1
              with:
                  paths: ${{ matrix.service }}/target/site/jacoco/jacoco.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
                  min-coverage-overall: 70
                  min-coverage-changed-files: 80
                  title: Coverage Report - ${{ matrix.service }}
                  update-comment: true

    aggregate-coverage:
        name: Aggregate Coverage
        runs-on: ubuntu-latest
        needs: coverage

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download all coverage reports
              uses: actions/download-artifact@v4
              with:
                  path: coverage-reports

            - name: Display coverage summary
              run: |
                  echo "## 📊 Test Coverage Summary" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo "| Service | Line Coverage | Branch Coverage |" >> $GITHUB_STEP_SUMMARY
                  echo "|---------|--------------|-----------------|" >> $GITHUB_STEP_SUMMARY

                  for service in auth-service employee-service; do
                    if [ -f "coverage-reports/coverage-report-$service/index.html" ]; then
                      echo "| $service | ✅ | ✅ |" >> $GITHUB_STEP_SUMMARY
                    fi
                  done
